apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: default
spec:
  ports:
  - nodePort: 30638
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
      name: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: galera:3306
        - name: WORDPRESS_DB_PASSWORD
          value: passw0rd
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_NAME
          value: wordpress
        image: wordpress:4.6
        imagePullPolicy: IfNotPresent
        name: wordpress
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
      dnsPolicy: ClusterFirst

