apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale
  namespace: default
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-nginx
  targetCPUUtilizationPercentage: 10
