apiVersion: v1beta1
id: storage22
desiredState:
  manifest:
    version: v1beta1
    id: storage22
    containers:
      - name: redis1
        image: dockerfile/redis
        ports:
          - containerPort: 6379
            hostPort: 6380
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis
      - name: redis2
        image: kubernetes/heapster_influxdb
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis
    volumes:
      - name: redis-persistent-storage
        source:
          emptyDir: {}
