apiVersion: v1beta1
id: storage
desiredState:
  manifest:
    version: v1beta1
    id: storage
    containers:
      - name: gyliu1
        image: dockerfile/redis
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis/1
            readOnly: true
    containers:
      - name: gyliu2
        image: dockerfile/redis
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis/2
    volumes:
      - name: redis-persistent-storage
        source:
          emptyDir: {}
