apiVersion: v1beta1
id: storage4
desiredState:
  manifest:
    version: v1beta1
    id: storage4
    containers:
      - name: redis
        image: dockerfile/redis
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis
    volumes:
      - name: redis-persistent-storage
        source:
            hostDir:
                path: /tmp
