apiVersion: v1beta1
id: storage5
desiredState:
  manifest:
    version: v1beta1
    id: storage5
    containers:
      - name: redis51
        image: dockerfile/redis
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis/1
            readOnly: true
      - name: redis52
        image: dockerfile/redis
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis/2
    volumes:
      - name: redis-persistent-storage
        source:
            hostDir:
                path: /tmp
