heat_template_version: 2013-05-23
description: >
  Heat template to deploy EGO services
resources:
  hadc:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      desired_capacity: 1
      max_size: 3
      resource:
        type: IBMInc::EGO::Activity
        properties:
          description: 'data nodes'
          control_policy: {
            start_type: 'AUTOMATIC',
            max_restarts: 10,
            dependency: {
              dtype: 'conditional',
              satisfy: 'STARTED',
              keep: 'STARTED',
              auto_start: 'TRUE',
              svc_name: 'hadm',
            }
          }
          activity_description: {
            htype: 'all',
            activity_specification: {
              command: 'sleep 10000',
              job_controller: 'sleep 10000'
            }
          }
