---
  apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    name: "kube-applier"
    namespace: "kube-system"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: "kube-applier"
      spec:
        containers:
          - name: "kube-applier"
            command:
              - "/kube-applier"
            env:
              - name: "REPO_PATH"
                value: "/k8s/resources/k8s/example"
              - name: "LISTEN_PORT"
                value: "2020"
            image: "jaxxstorm/kube-applier:v0.2.0"
            ports:
              - containerPort: 2020
            volumeMounts:
              - name: "git-repo"
                mountPath: "/k8s"
          - name: "git-sync"
            command:
              - "/git-sync"
            env:
              - name: "GIT_SYNC_REPO"
                value: "https://github.com/gyliu513/work.git"
              - name: "GIT_SYNC_DEST"
                value: "resources"
            image: "gcr.io/google_containers/git-sync:v2.0.6"
            ports:
              - containerPort: 2020
            volumeMounts:
              - name: "git-repo"
                mountPath: "/git"
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        volumes:
          - name: "git-repo"
            emptyDir: {}
