apiVersion: v1
kind: Service
metadata:
  name: sshd-server
spec:
  selector:
    app: sshd-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sshd-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sshd-server
    spec:
      containers:
      - name: sshd-server
        image: chenzhiwei/ubuntu:16.04
        ports:
        - containerPort: 22
