heat_template_version: 2013-05-23

description: >
  A document-based template to configure your Software Defined Environment.

parameters:
  # declaration of input parameters
  external_network_id:
    type: string
    description: Load Balancer Pool Subnet ID
    default: ac3dd16d9-c201-46f1-b231-03b1f6cc3238
  flavor:
    type: string
    description: Flavor to be used for compute instance
    default: "m1.small"
  image:
    type: string
    description: Image used for servers
    default: lbaas

resources:
  ag_php:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 5
      resource:
        type: IBMInc::EGO::Activity
        properties:
          containers:
            - description: 'web server'
              name: nginx
              image: dockerfile/nginx
              memory: 200m
              cmd: cmd1
              volumeMounts:
                - name: www-data
                  mountPath: /srv/www
                  readOnly: True
            - description: 'git monitor'
              name: git-monitor
              image: kubernetes/git-monitor
              memory: 200m
              cmd: cmd2
              env:
                - name: xx
                  value: xx
                - name: xx
                  value: xx
              volumeMounts:
                - name: www-data
                  mountPath: /data
          svc_name: 'www'
          control_policy: {
            start_type: 'AUTOMATIC',
            max_restarts: 10
          }
          allocation_specification: {
            consumer_id: '/ClusterServices/EGOClusterServices',
            resource_specification: {
              resource_group: 'InternalResourceGroup',
              resource_requirement: 'select(prsdemo3)',
            }
          }
          activity_description: {
            htype: 'all',
            activity_specification: {
              command: ['/usr/sbin/sshd -D'],
              job_controller: 'sleep 10000'
            }
          }

