version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - back-tier
      
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - back-tier
